### ISSUE TITLE
Could Not Establish Connection

### ISSUE THREAD

**Issue by MikeSofaer** [adrianandrei-ca/pgunit#1]
Hi,

I'm running a very simple test, and it tells me it can't establish a connection:

`par=# select * from test_run_all();
        test_name        | successful | failed | errorneous |         error_message          |    duration
-------------------------+------------+--------+------------+--------------------------------+-----------------
 test_case_user_create_1 | f          | f      | t          | could not establish connection | 00:00:00.000734
(1 row)`

What does this mean, and what do I do? What is it trying to connect to?

**Comment by adrianandrei-ca** [comment]
The autonomous transactions are implemented by connections to itself. For some reason that fails and we do not log the details.

No worries though, please do a follow through to get the details:
select test_case_user_create_1();

If you still need hints please post it here.

-AA
