### ISSUE TITLE
'could not establish connection' DBLINK error

### ISSUE THREAD

**Issue by jarnaldich** [adrianandrei-ca/pgunit#11]
Tests were failing with 'could not establish connection' DBLINK error on Postgresql 9.6. I am using a superuser that requires password authentication. It looks like the test_dblink_connect function does not add username= and password= in the connection string.

I managed to write a workaround by adding an additional setting that holds additional string parameters. You can see the workaround in my fork: https://github.com/jarnaldich/pgunit/commit/9ce8d6237b7aefc90b62a40a814d76f9078f2d65

Maybe I just did something stupid there or there is a better way to solve this. Otherwise, I can send a PR if needed.

**Comment by adrianandrei-ca** [comment]
Looks good to me.
