### ISSUE TITLE
Running tests as non-superuser

### ISSUE THREAD

**Issue by yallie** [adrianandrei-ca/pgunit#5]
Everything works fine when I connect as `postgres` (superuser).
But when I run tests as non-superuser, I get this error:
```
ErrorCode: -2147467259
Severity: ERROR, Code: 2F003, Line: 2660, Position:
ErrorMessage: password is required
Detail: Non-superusers must provide a password in the connection string.
```

Looks like `dblink_connect` [requires passwords for non-superuser](http://stackoverflow.com/questions/7031737/non-superuser-cannot-connect-if-the-server-does-not-request-a-password-while-usi).
The suggested workaround is to use `dblink_connect_u` instead.

I've just tested it and it seems to work fine in both superuser and non-superuser modes.
The only caveat is that user should be granted the privilege to execute the function.

**Comment by adrianandrei-ca** [comment]
We can document this in troubleshooting area..

**Comment by yallie** [comment]
I've inspected the documentation on `dblink_connect_u()` and found that it's [considered insecure](https://www.postgresql.org/docs/current/static/contrib-dblink-connect-u.html) for the ordinal users. So I've changed a bit my solution so that I can avoid granting execute permissions to ordinal users.

**Comment by yallie** [comment]
Using `security definer` clause allows me to execute the function as superuser if it's created by superuser. Hence, no need to grant execute privileges on `dblink_connect_u` to ordinal users. I've tested my updated solution and it works fine with both superuser and ordinal user.

**Comment by adrianandrei-ca** [comment]
nice job.
